const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"建议类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJianyi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"投诉类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTousu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"行李类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXingli"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"建议管理",
                        "menuJump":"列表",
                        "tableName":"jianyi"
                    }
                ],
                "menu":"建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作人员投诉管理",
                        "menuJump":"列表",
                        "tableName":"tousu"
                    }
                ],
                "menu":"工作人员投诉管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "审核",
                            "修改",
                            "删除"
                        ],
                        "menu":"行李托运管理",
                        "menuJump":"列表",
                        "tableName":"xingli"
                    }
                ],
                "menu":"行李托运管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"工作人员管理",
                        "menuJump":"列表",
                        "tableName":"gongzuorenyuan"
                    }
                ],
                "menu":"工作人员管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"建议管理",
                        "menuJump":"列表",
                        "tableName":"jianyi"
                    }
                ],
                "menu":"建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"行李托运管理",
                        "menuJump":"列表",
                        "tableName":"xingli"
                    }
                ],
                "menu":"行李托运管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"工作人员",
        "tableName":"gongzuorenyuan"
    },
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"建议管理",
                        "menuJump":"列表",
                        "tableName":"jianyi"
                    }
                ],
                "menu":"建议管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"工作人员投诉管理",
                        "menuJump":"列表",
                        "tableName":"tousu"
                    }
                ],
                "menu":"工作人员投诉管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"行李托运管理",
                        "menuJump":"列表",
                        "tableName":"xingli"
                    }
                ],
                "menu":"行李托运管理"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"用户",
        "tableName":"yonghu"
    }
]
    }
}
export default menu;
